### ISSUE TITLE
Selendroid 0.11.0 makes three orphaned processes per mobile web test.

### ISSUE THREAD

**Issue by koichirok** [selendroid/selendroid#588] opened 2014-09-11 09:15 UTC
Selendroid 0.11.0 makes three orphaned processes per mobile web test.
After sevral mobile web testing, device became unstable. (due to the memory exhaust caused by
orphaned processes?).

I checked following platform and got following result

* Android 4.0.4, 4.1.2 and 4.3: child processes are orphaned after test.
* Android 4.4.2: Seems no probrem. No orphaned processes are left.

This behavior introduced between 08ccefa955c3198ac0afd412158e0ff76b5c01fe and 08ccefa955c3198ac0afd412158e0ff76b5c01fe

How To Reproduce:

1. run 0.11.0 release of selendroid-standalone server for mobile web testing:
<pre>
java -jar selendroid-standalone-0.11.0-with-dependencies.jar
</pre>
2. Run mobile web test as you like. While running test, io.selendroid.androiddriver processes are like blow:
<pre>
% adb shell ps | grep selendroid
u0_a295   4706  218   560536 91624 ffffffff 00000000 S io.selendroid.androiddriver
u0_a295   4742  4706  515456 41412 ffffffff 00000000 S io.selendroid.androiddriver
u0_a295   4743  4706  515456 41548 ffffffff 00000000 S io.selendroid.androiddriver
u0_a295   4746  4706  516224 42488 ffffffff 00000000 S io.selendroid.androiddriver
</pre>
3. After finishing mobile web test. there are 3 chile processes orphaned:
<pre>
adb shell ps | grep selendroid
u0_a295   4742  1     515456 41412 ffffffff 00000000 S io.selendroid.androiddriver
u0_a295   4743  1     515456 41548 ffffffff 00000000 S io.selendroid.androiddriver
u0_a295   4746  1     516224 42488 ffffffff 00000000 S io.selendroid.androiddriver
</pre>
4. If you run another mobile web test, you will get three more orphaned processes.

**Comment by saral** [comment] 2015-01-04 12:48
I guess this is fixed by this [commit](https://github.com/saral/selendroid/commit/1d8225e667699454b602d61e846747b37200ccb0).

Here is the corresponding [PullRequest](https://github.com/selendroid/selendroid/pull/768).

**Comment by saral** [comment] 2015-01-08 12:23
According to my tests this issue is already fixed. I guess, we can close it.
[https://github.com/selendroid/selendroid/commit/11e08a8c94121cb580809514bc342da61d531dee]

**Comment by koichirok** [comment] 2015-01-11 08:49
Sorry for delay.

I've tested on my Device with "selendroid-standalone-0.13.0-20150108.185733-38-with-dependencies.jar".

On my device, problem seems to be improved (orphan processes are reduced) but still resolved.

Now selendroid works sometimes fine (no orphan processes are remained) but sometimes not (1 orphan process is remained)

**Comment by asm89** [comment] 2015-06-29 16:49
I'm closing this issue due to inactivity.

If is a question rather than an issue, please send questions to the [selendroid user group](https://groups.google.com/forum/#!forum/selendroid).

 If you think it's an actual problem with selendroid and still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Closed by asm89** 2015-06-29 16:49 UTC
