### ISSUE TITLE
Staying background processes

### ISSUE THREAD

**Issue by Son-kun** [selendroid/selendroid#739] opened 2014-12-10 08:52 UTC
Hi, I have a problem with application processes survining after closing the application.
After a few hundreds of tests ran on my phone the amount of free memory is almost 0.
adb shell top on device returns list containing more than 30 process of my application.

```
adb shell top

User 11%, System 13%, IOW 25%, IRQ 0%
User 71 + Nice 0 + Sys 83 + Idle 285 + IOW 151 + IRQ 0 + SIRQ 4 = 594

  PID PR CPU% S  #THR     VSS     RSS PCY UID      Name
 1972  1  11% S   123 523328K  64200K  fg system   system_server
12401  0   5% S    16 376564K  45856K  fg system   com.android.settings
15162  0   1% R     1   1280K    516K     shell    top
11164  0   0% D     1      0K      0K     root     kworker/0:5
 8465  0   0% S     1      0K      0K     root     kworker/u:1
 1051  0   0% S     1      0K      0K     root     mmcqd/0
 1457  1   0% S    13  44948K   2028K  fg system   /system/bin/surfaceflinger
 2315  1   0% S    27 350452K  26856K  fg u0_a113  com.android.systemui
 1458  1   0% S     4 304280K  12024K     root     zygote
  633  1   0% D     1      0K      0K     root     kswapd0
11843  1   0% S     1    924K    388K     shell    logcat
 1492  0   0% S     7   6700K    360K     shell    /sbin/adbd
 4141  0   0% S     1      0K      0K     root     kworker/0:4
21815  1   0% S     1    920K    388K     shell    logcat
    3  0   0% S     1      0K      0K     root     ksoftirqd/0
  495  1   0% S     1      0K      0K     root     bdi-default
  497  0   0% S     1      0K      0K     root     kblockd
  547  1   0% S     1      0K      0K     root     bcmpmu59xxx-irq
  549  1   0% S     1      0K      0K     root     accy_wq
  557  1   0% S     1      0K      0K     root     khubd
  559  0   0% S     1      0K      0K     root     bcm_otg_events
  591  1   0% S     1      0K      0K     root     cfg80211
  595  0   0% S     1      0K      0K     root     bcmpmu_fg_wq
  617  0   0% S     1      0K      0K     root     rpciod
  627  0   0% S     1      0K      0K     root     khungtaskd
  634  0   0% S     1      0K      0K     root     fsnotify_mark
  635  0   0% S     1      0K      0K     root     ecryptfs-kthrea
  637  0   0% S     1      0K      0K     root     nfsiod
  639  0   0% S     1      0K      0K     root     crypto
  770  0   0% S     1      0K      0K     root     gp2a_prox_wq
  773  0   0% S     1      0K      0K     root     irq/392-acceler
  793  0   0% S     1      0K      0K     root     kona_sspi_spi.0
  810  0   0% S     1      0K      0K     root     dwc_otg
  813  0   0% S     1      0K      0K     root     DWC Notificatio
  824  0   0% S     1      0K      0K     root     mtp_read_send
  829  0   0% S     1      0K      0K     root     file-storage
  846  0   0% S     1      0K      0K     root     kpsmoused
  862  1   0% S     1      0K      0K     root     irq/373-ist30xx
  875  0   0% S     1      0K      0K     root     irq/163-COMP1
  876  0   0% S     1      0K      0K     root     irq/421-aci_acc
  879  1   0% S     1      0K      0K     root     RpcKThread
  880  0   0% S     1      0K      0K     root     RTCCAL
  914  0   0% S     1      0K      0K     root     spa_power_wq
  916  0   0% S     1      0K      0K     root     bcmpmu_throttle
  924  0   0% S     1      0K      0K     root     cfinteractive
  991  0   0% S     1      0K      0K     root     binder
  998  1   0% S     1      0K      0K     root     kcompcached
 1001  0   0% S     1      0K      0K     root     irq/156-caph-in
    1  1   0% S     1    480K    284K     root     /init
 1030  0   0% S     1      0K      0K     root     krfcommd
 1043  1   0% S     1      0K      0K     root     irq/391-sdio cd
 1049  0   0% S     1      0K      0K     root     Dsi0T
 1078  0   0% S     1      0K      0K     root     dump-wq
 1079  0   0% S     1      0K      0K     root     SysRpcKThread
 1080  0   0% S     1      0K      0K     root     deferwq
 1081  0   0% S     1      0K      0K     root     rt8973_workqueu
 1088  0   0% S     1    388K    116K     root     /sbin/ueventd
 1436  1   0% S     1      0K      0K     root     jbd2/mmcblk0p17
 1437  1   0% S     1      0K      0K     root     ext4-dio-unwrit
 1439  1   0% S     1      0K      0K     root     jbd2/mmcblk0p15
 1440  0   0% S     1      0K      0K     root     ext4-dio-unwrit
 1442  1   0% S     1      0K      0K     root     jbd2/mmcblk0p16
 1443  1   0% S     1      0K      0K     root     ext4-dio-unwrit
 1445  1   0% S     1      0K      0K     root     jbd2/mmcblk0p19
 1446  0   0% S     1      0K      0K     root     ext4-dio-unwrit
 1450  1   0% S     1    968K    172K     system   /system/bin/servicemanager
 1451  1   0% S     4  16220K    448K     root     /system/bin/vold
 1454  0   0% S     8  10520K    984K     root     /system/bin/netd
 1455  0   0% S     1   1008K    160K     root     /system/bin/debuggerd
 1456  0   0% S     3   4240K    160K     system   /system/bin/npsmobex
 1459  0   0% S     2  13344K    288K  fg drm      /system/bin/drmserver
 1460  0   0% S     8  52120K   1284K  fg media    /system/bin/mediaserver
 1461  1   0% S     1   1020K    260K     install  /system/bin/installd
 1463  0   0% S     1   2160K    204K     keystore /system/bin/keystore
 1464  0   0% S     2   4876K    276K     radio    /system/bin/at_distributor
 1465  0   0% S     2   1920K    176K     system   /system/bin/sensord
 1466  0   0% S    10  23952K    684K     radio    /system/bin/rild
 1468  0   0% S     3   5548K    184K     system   /system/bin/atx
 1470  1   0% S     3   6176K    192K     system   /system/bin/bkmgrd
 1471  0   0% S     2   2160K    240K     system   /system/bin/usb_portd
 1491  0   0% S     3  11348K    260K     gps      /system/bin/glgps
 1513  0   0% S    21  27208K    500K     system   atxd
 1909  1   0% S     1      0K      0K     root     kworker/1:1
 2272  1   0% S    13 327748K  18104K  fg u0_a8    android.process.acore
 2385  1   0% S    25 349884K  19620K  fg radio    com.android.phone
 2530  1   0% S     9 312296K  15692K  fg u0_a8    com.sec.android.provider.logsprovide
 2693  0   0% S     9 312104K  15584K  fg u0_a69   com.sec.android.pagebuddynotisvc
 2697  1   0% S     9 312124K  15520K  fg u0_a127  com.sec.android.sCloudRelayData
 2701  1   0% S    11 315024K  16280K  fg u0_a21   com.samsung.android.providers.contex
 3397  1   0% S     1      0K      0K     root     kworker/u:0
 4708  0   0% S     1 343312K   9072K  fg u0_a130  my.application.tested
 4709  1   0% S     1 343312K   9084K  fg u0_a130  my.application.tested
 5319  0   0% S     1 343312K   9604K  fg u0_a130  my.application.tested
 5767  1   0% S     1 339776K  20324K  fg u0_a130  my.application.tested
 6079  1   0% S     1      0K      0K     root     wl_event_handle
 6086  1   0% S     1      0K      0K     root     dhd_watchdog_th
 6087  1   0% S     1      0K      0K     root     dhd_dpc
 6088  0   0% S     1      0K      0K     root     dhd_sysioc
 6093  1   0% S     1   3692K    784K     wifi     /system/bin/wpa_supplicant
 6097  1   0% S     1   2804K    476K     wifi     /system/bin/p2p_supplicant
 6102  1   0% S     1   1076K    360K     dhcp     /system/bin/dhcpcd
 6957  0   0% S     1      0K      0K     root     kworker/0:0
 7938  0   0% S     1 344464K  20564K  fg u0_a130  my.application.tested
 8142  1   0% S     1      0K      0K     root     kworker/1:3
 9495  0   0% S     1 343312K  20308K  fg u0_a130  my.application.tested
10099  0   0% S     9 314916K  16032K  fg bluetoot com.android.bluetooth
10118  1   0% S    11 314316K  15564K  fg u0_a94   com.sec.phone
10209  1   0% S     1 345488K  20420K  fg u0_a130  my.application.tested
11504  1   0% S     1      0K      0K     root     migration/1
11506  1   0% S     1      0K      0K     root     ksoftirqd/1
11561  0   0% S     2   4520K    516K     system   /system/bin/atx
12056  1   0% S     9 312228K  16036K  fg u0_a51   com.sec.android.app.keyguard
12300  1   0% S     9 312088K  15492K  bg u0_a37   com.android.location.fused
12911  0   0% S    10 313648K  15744K  fg system   com.android.MtpApplication
13316  1   0% S     1 338652K  20176K  fg u0_a130  my.application.tested
13556  1   0% S     1 344408K   7528K  fg u0_a130  my.application.tested
13580  1   0% S    12 315220K  15996K  fg u0_a23   com.android.defcontainer
13988  1   0% S     1      0K      0K     root     kworker/1:0
14182  0   0% S     1 343312K  20328K  fg u0_a130  my.application.tested
14183  1   0% S     1 343312K  20336K  fg u0_a130  my.application.tested
14493  1   0% S     1      0K      0K     root     kworker/1:2
14557  0   0% S     1 343084K  20052K  fg u0_a130  my.application.tested
14715  0   0% S     1      0K      0K     root     flush-179:0
14868  0   0% S     1      0K      0K     root     kworker/0:2
14935  1   0% S    17 361832K  25524K  bg u0_a16   com.google.process.gapps
14959  1   0% S    14 353756K  26880K  bg u0_a16   com.google.android.gms
14979  1   0% S    30 370540K  32244K  bg u0_a16   com.google.process.location
15011  1   0% S    15 354912K  24252K  bg u0_a16   com.google.android.gms.wearable
15160  0   0% S     1    884K    452K     shell    /system/bin/sh
15163  1   0% S    11 315164K  22500K  bg u0_a34   com.fmm.dm
15690  1   0% S     1 342068K   7700K  fg u0_a130  my.application.tested
15693  1   0% S     1 344352K   7692K  fg u0_a130  my.application.tested
15852  1   0% S     1      0K      0K     root     kworker/u:2
16263  0   0% S     1 344420K  20440K  fg u0_a130  my.application.tested
16871  0   0% S     1 339828K  20300K  fg u0_a130  my.application.tested
17839  1   0% S     1 343312K  20284K  fg u0_a130  my.application.tested
18382  1   0% S     1 343312K  12060K  fg u0_a130  my.application.tested
18748  0   0% S     1 345244K  21428K  fg u0_a130  my.application.tested
18953  0   0% S     1 343312K   7692K  fg u0_a130  my.application.tested
18954  1   0% S     1 343312K   7692K  fg u0_a130  my.application.tested
19348  0   0% S     1 337628K   7632K  fg u0_a130  my.application.tested
19349  1   0% S     1 337628K   7632K  fg u0_a130  my.application.tested
19352  1   0% S     1 344352K   7624K  fg u0_a130  my.application.tested
19919  0   0% S     1 343052K  20008K  fg u0_a130  my.application.tested
20574  1   0% S     1 338772K  20252K  fg u0_a130  my.application.tested
21250  0   0% S     1      0K      0K     root     kworker/0:3
22261  1   0% S     1 339788K  20196K  fg u0_a130  my.application.tested
22692  0   0% S     1 343312K   7648K  fg u0_a130  my.application.tested
22803  0   0% S     1 339692K  19936K  fg u0_a130  my.application.tested
28822  1   0% S     1 343084K  20092K  fg u0_a130  my.application.tested
32298  1   0% S     1 343312K   8216K  fg u0_a130  my.application.tested
32446  0   0% S     1 343312K  20308K  fg u0_a130  my.application.tested
 1009  0   0% S     1      0K      0K     root     AudioCtrlWq
    2  1   0% S     1      0K      0K     root     kthreadd
    6  0   0% S     1      0K      0K     root     migration/0
   10  1   0% S     1      0K      0K     root     cpuset
   11  1   0% S     1      0K      0K     root     khelper
   15  1   0% S     1      0K      0K     root     suspend
   16  1   0% S     1      0K      0K     root     suspend_sys_syn
   80  1   0% S     1      0K      0K     root     bcm_hsotgctrl_e
   84  0   0% S     1      0K      0K     root     kworker/0:1
   87  1   0% S     1      0K      0K     root     i2c_master_rese
   89  1   0% S     1      0K      0K     root     i2c_master_rese
   91  1   0% S     1      0K      0K     root     i2c_master_rese
   96  1   0% S     1      0K      0K     root     i2c_master_rese
   99  1   0% S     1      0K      0K     root     i2c_master_rese
  493  0   0% S     1      0K      0K     root     sync_supers
```

Is it possible that selendroid does not close processes propertly?

**Comment by saral** [comment] 2015-01-08 12:20
Can you please check if this issue is fixed in the latest snapshot? Because a related issue was fixed.

**Comment by Son-kun** [comment] 2015-02-02 14:43
I was checked that problem on 0.13 and still occur.

**Comment by asm89** [comment] 2015-06-29 16:26
I'm closing this issue due to inactivity. If you still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Closed by asm89** 2015-06-29 16:26 UTC
