### ISSUE TITLE
INSTRUMENTATION_FAILED when using selendroid

### ISSUE THREAD

**Issue by randoum** [selendroid/selendroid#805] opened 2015-02-09 12:31 UTC
Hi !

I was trying to fix this issue on my own since few days, but cannot find any working solution.
I am using Appium and Selendroid, and I get a blocking INSTRUMENTATION_FAILED error.

I tried with :
- Emulator v4.4.2
- Emulator v4.2.2
- Real device v4.2.2

The app is compiled by Cordova v4.2.0, but I got the same with an app compiled with RhoMobile v5.0.2.

Please note that when I use Appium without Selendroid (simply by commenting out `automationName: 'selendroid'` from the capacities) I don't have the problem.

Any advise will be greatly appreciated, I've been stuck for a week and really don't know what to do anymore.

Thanks in advance

```
info: Welcome to Appium v1.3.4 (REV e44a41b03cfc57165e0802c96d438cfbe7f5deb1)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"udid":"192.168.56.102:5555"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"","deviceName":"Android Emulator","platformName":"android","platformVersion":"4.2.2","automationName":"selendroid","app":"/workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk","appPackage":"com.launchfeedapp.client"}}
info: Client User-Agent string: appium/ruby_lib/6.0.0
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] Creating new appium session adee45c5-aeda-4ea3-b7a2-bfd2ea32b9b3
info: [debug] Starting selendroid server
info: [debug] Getting Java version
info: Java version is: 1.7.0_17
info: [debug] Checking whether adb is present
info: [debug] Using adb from /opt/android-sdk-linux/platform-tools/adb
info: [debug] Checking whether selendroid is built yet
info: [debug] Selendroid server exists!
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device 192.168.56.102:5555
info: [debug] Setting device id to 192.168.56.102:5555
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 wait-for-device
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /opt/android-sdk-linux/build-tools/19.1.0/aapt
info: [debug] Checking if has internet permission from manifest.
info: [debug] executing cmd: /opt/android-sdk-linux/build-tools/19.1.0/aapt dump badging /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /opt/android-sdk-linux/build-tools/19.1.0/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /opt/android-sdk-linux/build-tools/19.1.0/aapt dump badging /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] badging package: com.launchfeedapp.client
info: [debug] badging act: com.launchfeedapp.client.CordovaApp
info: [debug] Parsed package and activity are: com.launchfeedapp.client/com.launchfeedapp.client.CordovaApp
info: [debug] Rebuilt selendroid server already exists, no need to rebuild it with a new manifest
info: [debug] Checking signed status of /tmp/selendroid.com.launchfeedapp.client.apk
info: [debug] Checking app cert for /tmp/selendroid.com.launchfeedapp.client.apk.
info: [debug] executing cmd: java -jar /opt/appium/submodules/appium-adb/jars/verify.jar /tmp/selendroid.com.launchfeedapp.client.apk
info: [debug] Checking signed status of /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] Checking app cert for /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk.
info: [debug] executing cmd: java -jar /opt/appium/submodules/appium-adb/jars/verify.jar /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] App already signed.
info: [debug] Zip-aligning /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /opt/android-sdk-linux/build-tools/19.1.0/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /opt/android-sdk-linux/build-tools/19.1.0/zipalign -f 4 /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk /tmp/11519-10539-1c4tvpd/appium.tmp
info: [debug] App already signed.
info: [debug] Zip-aligning /tmp/selendroid.com.launchfeedapp.client.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /opt/android-sdk-linux/build-tools/19.1.0/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /opt/android-sdk-linux/build-tools/19.1.0/zipalign -f 4 /tmp/selendroid.com.launchfeedapp.client.apk /tmp/11519-10539-1twa8ly/appium.tmp
info: [debug] Rebuilt selendroid apk does not exist, uninstalling any instances of it on device to make way for new one
info: [debug] Uninstalling com.launchfeedapp.client.selendroid
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "am force-stop com.launchfeedapp.client.selendroid"
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 uninstall com.launchfeedapp.client.selendroid
info: [debug] App was not uninstalled, maybe it wasn't on device?
info: [debug] Getting install status for com.launchfeedapp.client.selendroid
info: [debug] Getting device API level
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 17
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "pm list packages -3 com.launchfeedapp.client.selendroid"
info: [debug] App is not installed
info: [debug] Rebuilt selendroid is not installed, installing it
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 install -r "/tmp/selendroid.com.launchfeedapp.client.apk"
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language: 
info: [debug] java -jar "/opt/appium/submodules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk" "/tmp/com.launchfeedapp.client" 
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk.
info: [debug] executing cmd: java -jar /opt/appium/submodules/appium-adb/jars/verify.jar /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] App already signed.
info: [debug] Zip-aligning /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /opt/android-sdk-linux/build-tools/19.1.0/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /opt/android-sdk-linux/build-tools/19.1.0/zipalign -f 4 /workspace/launch_feed_client/platforms/android/ant-build/CordovaApp-debug.apk /tmp/11519-10539-1qrf67s/appium.tmp
info: [debug] MD5 for app is 692dc50a7809869a92c96a3c4d1f006b
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "ls /data/local/tmp/692dc50a7809869a92c96a3c4d1f006b.apk"
info: [debug] Getting install status for com.launchfeedapp.client
info: [debug] Getting device API level
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 17
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "pm list packages -3 com.launchfeedapp.client"
info: [debug] App is installed
info: App is already installed, resetting app
info: [debug] Running fast reset (stop and clear)
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "am force-stop com.launchfeedapp.client"
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "pm clear com.launchfeedapp.client"
info: [debug] Forwarding system:8080 to device:8080
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 forward tcp:8080 tcp:8080
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 install "/opt/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 install "/opt/appium/build/unlock_apk/unlock_apk-debug.apk"
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 192.168.56.102:5555 shell "am instrument -e main_activity 'com.launchfeedapp.client.CordovaApp' com.launchfeedapp.client.selendroid/io.selendroid.server.ServerInstrumentation"
error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.launchfeedapp.client.selendroid/io.selendroid.server.ServerInstrumentation
	at com.android.commands.am.Am.runInstrument(Am.java:676)
	at com.android.commands.am.Am.run(Am.java:119)
	at com.android.commands.am.Am.main(Am.java:82)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
	at dalvik.system.NativeStart.main(Native Method)
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.launchfeedapp.client.selendroid/io.selendroid.server.ServerInstrumentation
info: [debug] Error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.launchfeedapp.client.selendroid/io.selendroid.server.ServerInstrumentation
    at /opt/appium/submodules/appium-adb/lib/adb.js:1378:17
    at null.<anonymous> (/opt/appium/submodules/appium-adb/lib/adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.launchfeedapp.client.selendroid/io.selendroid.server.ServerInstrumentation\r)","origValue":"android.util.AndroidException: INSTRUMENTATION_FAILED: com.launchfeedapp.client.selendroid/io.selendroid.server.ServerInstrumentation\r"},"sessionId":null}
info: <-- POST /wd/hub/session 500 4544.083 ms - 392 
```

**Comment by operatiay** [comment] 2015-02-09 13:15
Hi @randoum, can you reproduce it with pure selendroid?

**Comment by lukeis** [comment] 2015-02-09 17:41
also your 'real' exception message will be in the `adb logcat` so please create a gist with the full output of that when you attempt to run your test.

Also keep in mind Cordova support was only recently introduced in 0.14 and was coded to one particular version of Cordova: 3.7.0, since you mention using 4.2.0, I don't think selendroid will work for you.

**Comment by randoum** [comment] 2015-02-09 23:45
@operatiay, @lukeis 
HI guys, thanks for your quick answers

Ok so did several tests

**1- Selendroid-standalone and test app**
This gives me a `SessionNotCreatedException` error. 

Did the test with a real device and with an emulator running on Genymotion. Both with API 4.2.2

The Emulator show in adb as a device, which is confusing me a bit, but perhaps it's how Genymotion works

```
$ adb devices
List of devices attached 
192.168.56.101:5555	device
```

Here is the git with the requested capabilities, the server status before running the test, and the selendroid-server logs:
- Genymotion with API 4.2.2 https://gist.github.com/randoum/ffdbcdbca377b9f653e3
- real device with API 4.2.2 https://gist.github.com/randoum/3f93b8d5cf30dca2ba4d

**2- Selendroid-standalone and my cordova app**
This gives me a `DeviceStoreException`, with the message: No devices are found. This can happen if the devices are in use or no device screen matches the required capabilities.

It mention a device screen problem, is it simply a question of screen size?

Here is the git with the requested capabilities, the server status before running the test, the selendroid-server logs, and the logcat: https://gist.github.com/randoum/eee489c08797380c6ba1

Please let me know if you need me to perform other test, and many thanks for your help

**Comment by lukeis** [comment] 2015-02-10 17:50
for 1-
The error message says it doesn't have the application requested... which is correct because you're using the wrong capabilities aut: 'com.launchfeedapp.client:0.0.1'  is not the test app.
It should be "io.selendroid.testapp:0.14.0"

for 2- 
Not certain what is going on here... the log seems to start up the app, but then it crashes? is that what you're seeing? The logcat suspiciously doesn't show any stack trace, only:
I/ActivityManager(  448): Force stopping package com.launchfeedapp.client appid=10082 user=0
I/ActivityManager(  448): Killing proc 7441:com.launchfeedapp.client/u0a10082: force stop com.launchfeedapp.client
W/ActivityManager(  448): Crash of app com.launchfeedapp.client running instrumentation ComponentInfo{io.selendroid.com.launchfeedapp.client/io.selendroid.server.ServerInstrumentation}
I/ActivityManager(  448): Force stopping package com.launchfeedapp.client appid=10082 user=0

But I can't see a cause of the force stop?

**Comment by asm89** [comment] 2015-06-29 16:16
I'm closing this issue due to inactivity. If you still experience the issue described on the latest release of selendroid feel free to file a new issue. If you do please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Closed by asm89** 2015-06-29 16:16 UTC
